Repository Together-3team/petFrontend, pull requests merged in 2024-05, with the labels that each got.

#2 [봉찬] 페이지별 레이아웃을 위한 getLayout 구현
  src/components/common/Layout/Main/Header/index.tsx
  src/components/common/Layout/Main/index.tsx
  src/components/common/Nav/Nav.module.scss
  src/components/common/Nav/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/test/events/index.tsx
  src/pages/test/products/[productId].tsx
Labels: feat

#8 [봉찬] pr 템플릿 리뷰 작성 가이드 추가
  .github/pull_request_template.md
Labels: refactor

#11 [봉찬] classnames 패키지 추가
  package-lock.json
  package.json
Labels: feat

#12 [민영] 별점 컴포넌트 구현
  package-lock.json
  package.json
  src/components/review/StarRating.tsx
Labels: feat

#19 [봉찬] 10px = 1rem
  src/styles/reset.scss
Labels: feat

#21 [송은] Tag 컴포넌트 구현
  src/components/common/Tag/Tag.module.scss
  src/components/common/Tag/index.tsx
  src/pages/test/tag/index.tsx
Labels: feat

#22 [서인] Input 컴포넌트 구현
  package-lock.json
  package.json
  public/images/search.svg
  src/components/common/Input/Input.module.scss
  src/components/common/Input/InputLayout.tsx
  src/components/common/Input/index.tsx
  src/components/my/NicknameForm.tsx
  src/pages/test/input.tsx
  src/pages/test/nicknameForm.tsx
Labels: feat

#24 [민영] Textarea 컴포넌트 구현
  package-lock.json
  src/components/review/Textarea.module.scss
  src/components/review/Textarea.tsx
Labels: feat

#14 [지원] Button 컴포넌트 구현
  src/components/common/Button/Button.module.scss
  src/components/common/Button/index.tsx
Labels: feat

#16 [지원] Dropdown 기능 구현
  package-lock.json
  package.json
  src/components/common/Dropdown/Dropdown.module.scss
  src/components/common/Dropdown/index.tsx
Labels: feat

#29 [봉찬] AWS CI/CD
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
Labels: feat

#30 [서인] ImageBox 컴포넌트 구현
  src/components/common/ImageBox/ImageBox.module.scss
  src/components/common/ImageBox/index.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/InputLayout.tsx
  src/components/common/Input/index.tsx
  src/components/my/NicknameForm.tsx
  src/pages/test/imageBox.tsx
  src/pages/test/input.tsx
Labels: feat

#35 [봉찬] AWS CI/CD 버그 수정
  appspec.yml
  deploy.sh
Labels: bug

#31 [민영] 프로필 이미지뱃지 컴포넌트 구현, review 컴포넌트 폴더 이동
  package-lock.json
  public/images/defaultProfile.svg
  src/components/common/Badge/ProfileImgBadge.module.scss
  src/components/common/Badge/ProfileImgBadge.tsx
  src/components/common/review/StarRating.tsx
  src/components/common/review/Textarea.module.scss
  src/components/common/review/Textarea.tsx
Labels: feat

#37 [봉찬] PR Vercel 미리보기
  .github/workflows/fork-deploy.yml
  .github/workflows/vercel-preview.yml
  scripts/fork-build.sh
  src/pages/test/vercel/index.tsx
Labels: feat

#41 [서인] BottomModal 공통 컴포넌트 구현
  src/components/common/Input/Input.module.scss
  src/components/common/Modal/BottomModal/BottomModal.module.scss
  src/components/common/Modal/BottomModal/ModalBase.tsx
  src/components/common/Modal/BottomModal/index.tsx
  src/components/common/Modal/Portal.ts
  src/hooks/useModal.ts
  src/pages/_document.tsx
  src/pages/test/My.module.scss
  src/pages/test/my.tsx
Labels: feat

#43 [봉찬] 공통 스타일 작업
  src/pages/Home.module.scss
  src/styles/colors.scss
  src/styles/globals.scss
  src/styles/media.scss
  src/styles/mixin.scss
  src/styles/z-index.scss
Labels: feat

#44 [봉찬] Nav 작업
  next.config.mjs
  package-lock.json
  package.json
  src/assets/svgs/heart.svg
  src/assets/svgs/home.svg
  src/assets/svgs/person.svg
  src/assets/svgs/search-bold.svg
  src/components/common/Layout/Main/Footer/index.tsx
  src/components/common/Layout/Main/Header/index.tsx
  src/components/common/Layout/Main/index.tsx
  src/components/common/Nav/Bottom/NavBottom.module.scss
  src/components/common/Nav/Bottom/index.tsx
  src/components/common/Nav/Nav.module.scss
  src/components/common/Nav/Top/NavTop.module.scss
  src/components/common/Nav/Top/index.tsx
  src/components/common/Nav/index.tsx
  src/data/topMenus.json
  src/fonts/SUIT-Variable.woff2
  src/hooks/index.ts
  src/hooks/useDragScroll.ts
  src/hooks/useScrollIntoViewWithPath.ts
  src/pages/test/events/index.tsx
  src/pages/test/liked/index.tsx
  src/pages/test/my/index.tsx
  src/pages/test/products/[productId].tsx
  src/pages/test/search/index.tsx
  src/styles/fonts.scss
  src/styles/reset.scss
  src/utils/getDynamicPath.ts
  src/utils/index.ts
Labels: feat

#40 [지원] 장바구니 UI 구현
  package-lock.json
  package.json
  public/images/exampleProductImg.jpg
  src/components/cart/Card.module.scss
  src/components/cart/Card.tsx
  src/pages/Cart/Cart.module.scss
  src/pages/Cart/index.tsx
Labels: feat

#50 [봉찬] react-query 설정
  .eslintrc.json
  package-lock.json
  package.json
  src/pages/_app.tsx
Labels: feat

#54 [서인] 카카오 로그인 요청 구현
  .gitignore
  env.d.ts
  src/components/auth/Login/KakaoLogin.tsx
  src/components/auth/Login/index.tsx
  src/constants/oAuth.ts
  src/pages/test/login.tsx
Labels: feat

#64 [봉찬] 공통 폰트 mixin 선언
  src/styles/fonts.scss
  src/styles/reset.scss
Labels: feat

#57 [서인] 구글 로그인 요청
  package-lock.json
  src/components/auth/Login/GoogleLogin.tsx
  src/components/auth/Login/index.tsx
  src/constants/oAuth.ts
  src/pages/test/login.tsx
Labels: feat

#60 [민영] 리뷰 박스 컴포넌트 구현
  public/images/defaultProfile.svg
  src/assets/images/defaultProfileImg.png
  src/components/common/Badge/ProfileImgBadge.tsx
  src/components/common/review/ReviewBox.module.scss
  src/components/common/review/ReviewBox.tsx
  src/components/common/review/Textarea.module.scss
  src/components/common/review/Textarea.tsx
  src/utils/formatDate.ts
Labels: feat

#66 [서인] my페이지 / 로그인 UI 구현
  src/assets/svgs/google-logo.svg
  src/assets/svgs/kakao-logo.svg
  src/components/auth/Login/GoogleLogin.tsx
  src/components/auth/Login/KakaoLogin.tsx
  src/components/auth/Login/index.tsx
  src/components/auth/LoginButton/GoogleLogin.tsx
  src/components/auth/LoginButton/KakaoLogin.tsx
  src/components/auth/LoginButton/Login.module.scss
  src/components/auth/LoginButton/index.tsx
  src/components/auth/NicknameForm.tsx
  src/components/common/ImageBox/ImageBox.module.scss
  src/components/common/ImageBox/index.tsx
  src/pages/my/My.module.scss
  src/pages/my/index.tsx
  src/pages/test/login.tsx
  src/pages/test/my.tsx
  src/pages/test/nicknameForm.tsx
  src/styles/colors.scss
Labels: feat

#67 [봉찬] AWS CI/CD 버그 수정
  appspec.yml
  deploy.sh
  scripts/aws-deploy.sh
Labels: bug

#56 [봉찬] Layout 초안 작업
  package-lock.json
  src/assets/fonts/SUIT-Variable.woff2
  src/components/common/Button/ScrollTop/ScrollTopButton.module.scss
  src/components/common/Button/ScrollTop/index.tsx
  src/components/common/Layout/Main/Footer/MainFooter.module.scss
  src/components/common/Layout/Main/Footer/index.tsx
  src/components/common/Layout/Main/Header/MainHeader.module.scss
  src/components/common/Layout/Main/Header/index.tsx
  src/components/common/Layout/Main/MainLayout.module.scss
  src/components/common/Layout/Main/index.tsx
  src/components/common/Layout/Root/RootLayout.module.scss
  src/components/common/Layout/Root/index.tsx
  src/components/common/Modal/BottomModal/BottomModal.module.scss
  src/components/common/Nav/Bottom/NavBottom.module.scss
  src/components/common/Nav/Top/NavTop.module.scss
  src/pages/Home.module.scss
  src/pages/HomePage.module.scss
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/test/my/index.tsx
  src/styles/fonts.scss
  src/styles/globals.scss
  src/styles/mixin.scss
  src/styles/sizes.scss
  src/styles/z-index.scss
Labels: feat

#58 [송은] Card 컴포넌트
  package-lock.json
  src/assets/images/rectangle.png
  src/assets/svgs/rectangle.svg
  src/assets/svgs/search.svg
  src/assets/svgs/sole-red.svg
  src/assets/svgs/sole.svg
  src/assets/svgs/star.svg
  src/assets/svgs/stock.svg
  src/assets/svgs/thumbs-up.svg
  src/components/common/Card/Card.module.scss
  src/components/common/Card/index.tsx
  src/components/common/Tag/Tag.module.scss
  src/components/common/Tag/index.tsx
  src/pages/test/card/Card.module.scss
  src/pages/test/card/index.tsx
  src/pages/test/tag/index.tsx
Labels: feat
