Repository Together-3team/petFrontend, pull requests merged in 2024-06, with the labels that each got.

#74 [봉찬] 루트 레이아웃 padding 제거
  package-lock.json
  src/components/common/Layout/Main/Header/MainHeader.module.scss
  src/components/common/Layout/Main/MainLayout.module.scss
  src/components/common/Layout/Root/RootLayout.module.scss
  src/pages/HomePage.module.scss
  src/pages/index.tsx
Labels: refactor

#93 [민영] 상품상세페이지 -> 대표 리뷰 컴포넌트 구현
  package-lock.json
  src/components/common/review/HighlightReview.module.scss
  src/components/common/review/HighlightReview.tsx
  src/components/common/review/ReviewBox.module.scss
  src/components/common/review/ReviewBox.tsx
  src/components/common/review/ReviewSummary.module.scss
  src/components/common/review/ReviewSummary.tsx
  src/components/common/review/StarRating.module.scss
  src/components/common/review/StarRating.tsx
  src/components/common/review/Textarea.module.scss
  src/pages/test/review/index.tsx
Labels: feat

#78 [봉찬] 홈 페이지 / 배너 캐러셀
  package-lock.json
  package.json
  src/assets/images/test-carousel1.jpg
  src/assets/images/test-carousel2.jpg
  src/assets/images/test-carousel3.jpg
  src/assets/images/test-carousel4.jpg
  src/assets/images/test-carousel5.jpg
  src/components/common/Carousel/Banner/BannerCarousel.module.scss
  src/components/common/Carousel/Banner/index.tsx
  src/hooks/useSelectedSnapDisplay.ts
  src/pages/HomePage.module.scss
  src/pages/index.tsx
Labels: feat

#88 [봉찬] 카테고리 버튼
  src/components/common/Button/Category/CategoryButton.module.scss
  src/components/common/Button/Category/index.tsx
  src/components/common/Layout/Main/index.tsx
  src/hooks/useOutsideClick.ts
  src/styles/reset.scss
Labels: feat

#92 [송은] ShareModal
  src/components/common/Modal/BottomModal/BottomModal.module.scss
  src/components/common/Modal/BottomModal/ModalBase.tsx
  src/components/common/Modal/BottomShareModal/BottomShareModal.module.scss
  src/components/common/Modal/BottomShareModal/ModalBase.tsx
  src/components/common/Modal/BottomShareModal/index.tsx
  src/pages/test/my.tsx
  src/pages/test/sharemodal/ShareModalPage.module.scss
  src/pages/test/sharemodal/index.tsx
  src/styles/mixin.scss
Labels: feat

#96 [서인] onboarding 페이지 / UI 구현
  package-lock.json
  public/images/gray-check.png
  src/assets/images/gray-check.png
  src/assets/images/pink-check.png
  src/components/common/Button/Button.module.scss
  src/components/common/Button/index.tsx
  src/components/common/CheckOnly/CheckOnly.module.scss
  src/components/common/CheckOnly/index.tsx
  src/components/common/ImageBox/ImageBox.module.scss
  src/components/common/ImageBox/index.tsx
  src/pages/my/My.module.scss
  src/pages/onboarding/Onboarding.module.scss
  src/pages/onboarding/index.tsx
  src/pages/onboarding/welcome.tsx
  src/styles/mixin.scss
Labels: feat

#99 [민영] profileImgBadge 컴포넌트 기본 아이콘 수정
  package-lock.json
  src/assets/images/defaultProfileImg.png
  src/assets/svgs/profile-icon.svg
  src/components/common/Badge/ProfileImgBadge.module.scss
  src/components/common/Badge/ProfileImgBadge.tsx
  src/components/common/review/ReviewBox.module.scss
  src/components/common/review/ReviewBox.tsx
Labels: refactor

#103 [민영] 리뷰 전체 페이지 UI
  src/components/common/Badge/ProfileImgBadge.module.scss
  src/components/common/review/HighlightReview.module.scss
  src/components/common/review/HighlightReview.tsx
  src/components/common/review/RatingBox.module.scss
  src/components/common/review/RatingBox.tsx
  src/components/common/review/ReviewSummary.tsx
  src/pages/test/review/ReviewPage.module.scss
  src/pages/test/review/index.tsx
Labels: feat

#107 [봉찬] AWS CI/CD env 파일 누락
  .github/workflows/aws-deploy.yml
Labels: bug

#111 [봉찬] aws 배포 경로 수정
  appspec.yml
  scripts/aws-deploy.sh
Labels: refactor

#109 [봉찬] 헤더
  package-lock.json
  src/assets/svgs/cart.svg
  src/assets/svgs/heart.svg
  src/assets/svgs/home.svg
  src/assets/svgs/person.svg
  src/assets/svgs/search-bold.svg
  src/assets/svgs/search-detail.svg
  src/assets/svgs/search.svg
  src/components/common/BackButton/BackButton.module.scss
  src/components/common/BackButton/index.tsx
  src/components/common/Button/Cart/CartButton.module.scss
  src/components/common/Button/Cart/index.tsx
  src/components/common/Button/Search/SearchButton.module.scss
  src/components/common/Button/Search/index.tsx
  src/components/common/Layout/Header/Box/HeaderBox.module.scss
  src/components/common/Layout/Header/Box/index.tsx
  src/components/common/Layout/Header/Center/HeaderCenter.module.scss
  src/components/common/Layout/Header/Center/index.tsx
  src/components/common/Layout/Header/Left/HeaderLeft.module.scss
  src/components/common/Layout/Header/Left/index.tsx
  src/components/common/Layout/Header/Right/HeaderRight.module.scss
  src/components/common/Layout/Header/Right/index.tsx
  src/components/common/Layout/Header/Root/HeaderRoot.module.scss
  src/components/common/Layout/Header/Root/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/Main/Footer/MainFooter.module.scss
  src/components/common/Layout/Main/Footer/index.tsx
  src/components/common/Layout/Main/Header/MainHeader.module.scss
  src/components/common/Layout/Main/Header/index.tsx
  src/components/common/Layout/Main/MainLayout.module.scss
  src/components/common/Layout/Main/index.tsx
  src/components/common/Nav/Bottom/NavBottom.module.scss
  src/components/common/Nav/Bottom/index.tsx
  src/components/common/Nav/Top/index.tsx
  src/hooks/useScrollUpAndDown.ts
  src/pages/404.tsx
  src/pages/HomePage.module.scss
  src/pages/index.tsx
  src/pages/test/My.module.scss
  src/pages/test/events/index.tsx
  src/pages/test/liked/index.tsx
  src/pages/test/my.tsx
  src/pages/test/products/[productId].tsx
  src/pages/test/search/index.tsx
Labels: feat

#112 [민영] 상품상세페이지 -> 공동구매 UI
  src/assets/svgs/ampersand-icon.svg
  src/components/common/HighlightTeam/HighlightTeam.module.scss
  src/components/common/HighlightTeam/index.tsx
  src/components/common/review/HighlightReview.tsx
  src/pages/test/team/index.tsx
Labels: feat

#101 [송은] Zzim 컴포넌트
  package-lock.json
  src/assets/svgs/sole-gray.svg
  src/assets/svgs/sole-red.svg
  src/assets/svgs/sole.svg
  src/components/common/Card/Card.module.scss
  src/components/common/Card/index.tsx
  src/components/common/Zzim/Zzim.module.scss
  src/components/common/Zzim/index.tsx
  src/pages/test/card/Card.module.scss
  src/pages/test/card/index.tsx
  src/utils/zzim.ts
Labels: feat

#118 [민영] 공동구매 전체보기 페이지
  src/components/common/Team/HighlightTeam.module.scss
  src/components/common/Team/HighlightTeam.tsx
  src/components/common/Team/TeamDataCard.module.scss
  src/components/common/Team/TeamDataCard.tsx
  src/pages/test/review/index.tsx
  src/pages/test/team/TeamPage.module.scss
  src/pages/test/team/index.tsx
Labels: feat

#126 [민영] 별점 컴포넌트 text 추가
  package-lock.json
  src/components/common/review/StarRating.module.scss
  src/components/common/review/StarRating.tsx
Labels: feat

#123 [서인] my order 페이지 / UI 구현
  package-lock.json
  src/components/common/Button/Button.module.scss
  src/components/common/Button/index.tsx
  src/components/common/Card/Card.module.scss
  src/components/common/Card/index.tsx
  src/components/common/Tag/Tag.module.scss
  src/components/common/Tag/index.tsx
  src/components/order/OrderCard/OrderCard.module.scss
  src/components/order/OrderCard/index.tsx
  src/components/order/OrderFilterBar/OrderFilterBar.module.scss
  src/components/order/OrderFilterBar/index.tsx
  src/hooks/useIntersect.ts
  src/pages/my/order/Order.module.scss
  src/pages/my/order/empty.tsx
  src/pages/my/order/index.tsx
Labels: feat

#120 [지원] 경로명 수정 (Cart => cart)
  src/pages/cart/Cart.module.scss
  src/pages/cart/index.tsx
Labels: refactor

#129 [봉찬] Toast
  src/assets/svgs/check-white.svg
  src/assets/svgs/warning.svg
  src/components/common/Layout/Footer/FloatingBox/FloatingBox.module.scss
  src/components/common/Layout/Footer/FloatingBox/index.tsx
  src/components/common/Layout/Header/Root/HeaderRoot.module.scss
  src/components/common/Layout/Root/RootLayout.module.scss
  src/components/common/Layout/Root/index.tsx
  src/components/common/Nav/Bottom/NavBottom.module.scss
  src/components/common/Nav/Top/index.tsx
  src/components/common/Portal/index.tsx
  src/components/common/Toast/Provider/index.tsx
  src/components/common/Toast/Toast.module.scss
  src/components/common/Toast/index.tsx
  src/constants/portal.ts
  src/hooks/useOutsideClick.ts
  src/hooks/useScrollIntoViewWithPath.ts
  src/hooks/useToast.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/test/products/[productId].tsx
  src/styles/z-index.scss
  src/types/components/toast.ts
  src/types/index.ts
  src/utils/scrollToTargetX.ts
Labels: feat

#133 [지원] 상품 개별삭제 기능 구현
  src/apis/axiosInstance.ts
  src/constants/index.ts
  src/pages/cart/Cart.module.scss
  src/pages/cart/index.tsx
Labels: feat

#137 [지원] sessionStorage 사용, 낙관적 업데이트(useMutation), GET/DELETE/PUT api 연동
  .gitignore
  next.config.mjs
  src/apis/axiosInstance.ts
  src/apis/cartApi.ts
  src/components/cart/Card.tsx
  src/pages/cart/index.tsx
Labels: feat

#132 [송은] bottomSheet 컴포넌트
  package-lock.json
  package.json
  src/components/common/Modal/BottomSheet/BottomSheet.module.scss
  src/components/common/Modal/BottomSheet/Header.tsx
  src/components/common/Modal/BottomSheet/index.tsx
  src/hooks/useBottomSheet.ts
  src/hooks/usePreviousValue.ts
  src/pages/test/bottom-sheet/index.tsx
Labels: feat

#139 [민영] 리뷰 작성 페이지 UI
  package-lock.json
  src/pages/my/review/write/WritePage.module.scss
  src/pages/my/review/write/index.tsx
Labels: feat

#145 [송은] Tag 컴포넌트 수정
  src/components/common/Card/index.tsx
  src/components/common/Tag/Tag.module.scss
  src/components/common/Tag/index.tsx
  src/pages/test/tag/index.tsx
Labels: refactor

#140 [서인] accessToken으로 인증 처리
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  src/apis/authApi.ts
  src/apis/authAxiosInstance.ts
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/apis/userApi.ts
  src/components/auth/LoginButton/GoogleLogin.tsx
  src/components/auth/LoginButton/KakaoLogin.tsx
  src/components/auth/Menu/Menu.module.scss
  src/components/auth/Menu/index.tsx
  src/components/auth/SignupForm/UserAgreement.tsx
  src/components/auth/SignupForm/index.tsx
  src/components/common/Button/NextButton/index.tsx
  src/components/common/Input/index.tsx
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/pages/auth/google/callback.tsx
  src/pages/auth/kakao/callback.tsx
  src/pages/my/My.module.scss
  src/pages/my/index.tsx
  src/pages/my/menu.tsx
  src/pages/onboarding/Onboarding.module.scss
  src/pages/onboarding/index.tsx
  src/pages/onboarding/welcome.tsx
  src/pages/signup/Signup.module.scss
  src/utils/cookie.ts
  src/utils/signupFormSchema.ts
Labels: feat

#143 [서인] 주문 상세 페이지 / UI 구현
  package-lock.json
  src/components/order/OrderFilterBar/index.tsx
  src/pages/my/order/Order.module.scss
  src/pages/my/order/detail.tsx
Labels: feat

#150 [봉찬] 바텀시트, 모달 리팩토링
  package-lock.json
  package.json
  src/components/common/Modal/Base/BottomModal/BottomModal.module.scss
  src/components/common/Modal/Base/BottomModal/index.tsx
  src/components/common/Modal/Base/BottomSheet/BottomSheet.module.scss
  src/components/common/Modal/Base/BottomSheet/index.tsx
  src/components/common/Modal/Base/CenterModal/CenterModal.module.scss
  src/components/common/Modal/Base/CenterModal/index.tsx
  src/components/common/Modal/BottomSheet/BottomSheet.module.scss
  src/components/common/Modal/BottomSheet/Header.tsx
  src/components/common/Modal/BottomSheet/index.tsx
  src/components/common/Toast/Provider/index.tsx
  src/hooks/useBottomSheet.ts
  src/pages/HomePage.module.scss
  src/pages/index.tsx
  src/pages/test/bottom-sheet/index.tsx
  src/pages/test/sharemodal/index.tsx
  src/styles/z-index.scss
Labels: refactor

#151 [민영] 리뷰 상세보기 페이지 UI
  src/components/common/review/ReviewProductDataCard.module.scss
  src/components/common/review/ReviewProductDataCard.tsx
  src/pages/my/review/[reviewId]/ReviewDetailPage.module.scss
  src/pages/my/review/[reviewId]/index.tsx
  src/pages/my/review/write/index.tsx
Labels: feat

#142 [지원] 장바구니페이지 Header 컴포넌트 적용
  .gitignore
  package-lock.json
  package.json
  src/apis/cartApi.ts
  src/assets/images/check.json
  src/assets/images/paymentSuccess.png
  src/assets/images/withSuccess.png
  src/pages/cart/Cart.module.scss
  src/pages/cart/index.tsx
  src/pages/payment/Payment.module.scss
  src/pages/payment/PaymentSuccess.module.scss
  src/pages/payment/PaymentSuccessByCart.module.scss
  src/pages/payment/PaymentSuccessByWith.module.scss
  src/pages/payment/index.tsx
  src/pages/payment/paymentSuccess.tsx
  src/pages/payment/paymentSuccessByCart.tsx
  src/pages/payment/paymentSuccessByWith.tsx
Labels: feat

#153 [송은] deliveryEditPage
  package-lock.json
  package.json
  src/components/common/Input/Input.module.scss
  src/components/common/Input/index.tsx
  src/components/payment/AddressInput.module.scss
  src/components/payment/AddressInput.tsx
  src/pages/payment/delivery/edit/Edit.module.scss
  src/pages/payment/delivery/edit/index.tsx
  src/utils/deliveryFormSchema.ts
Labels: feat

#162 [서인] Onboarding 페이지 / api 연결
  next.config.mjs
  package-lock.json
  src/apis/authApi.ts
  src/apis/axiosInstance.ts
  src/apis/userApi.ts
  src/assets/images/logout-pets.png
  src/assets/images/selected-cat.png
  src/assets/images/selected-dog.png
  src/assets/images/unselected-cat.png
  src/assets/images/unselected-dog.png
  src/components/auth/LoginButton/Login.module.scss
  src/components/auth/Menu/index.tsx
  src/components/auth/SignupForm/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Card/index.tsx
  src/components/common/ImageBox/ImageBox.module.scss
  src/components/common/Input/Input.module.scss
  src/components/common/Input/index.tsx
  src/components/order/OrderCard/OrderCard.module.scss
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/pages/auth/google/callback.tsx
  src/pages/auth/kakao/callback.tsx
  src/pages/my/My.module.scss
  src/pages/my/index.tsx
  src/pages/my/info/index.tsx
  src/pages/my/order/Order.module.scss
  src/pages/my/order/detail.tsx
  src/pages/my/profile/index.tsx
  src/pages/onboarding/Onboarding.module.scss
  src/pages/onboarding/Welcome.module.scss
  src/pages/onboarding/index.tsx
  src/pages/onboarding/welcome.tsx
Labels: feat

#156 [봉찬] CardSlider
  src/assets/svgs/right-arrow-bold.svg
  src/components/common/Button/NextButtonTemp/NextButtonTemp.module.scss
  src/components/common/Button/NextButtonTemp/index.tsx
  src/components/common/Card/CardPlaceholder/CardPlaceholder.module.scss
  src/components/common/Card/CardPlaceholder/index.tsx
  src/components/common/Card/CardSlider/Base/Description/CardSliderDescription.module.scss
  src/components/common/Card/CardSlider/Base/Description/index.tsx
  src/components/common/Card/CardSlider/Base/Header/CardSliderHeader.module.scss
  src/components/common/Card/CardSlider/Base/Header/index.tsx
  src/components/common/Card/CardSlider/Base/Item/CardSliderItem.module.scss
  src/components/common/Card/CardSlider/Base/Item/index.tsx
  src/components/common/Card/CardSlider/Base/List/CardSliderList.module.scss
  src/components/common/Card/CardSlider/Base/List/index.tsx
  src/components/common/Card/CardSlider/Base/Root/CardSliderRoot.module.scss
  src/components/common/Card/CardSlider/Base/Root/index.tsx
  src/components/common/Card/CardSlider/Base/Title/CardSliderTitle.module.scss
  src/components/common/Card/CardSlider/Base/Title/index.tsx
  src/components/common/Card/CardSlider/Base/index.tsx
  src/components/common/Card/CardSlider/Hot/CardSliderHot.module.scss
  src/components/common/Card/CardSlider/Hot/index.tsx
  src/components/common/Card/CardSlider/Recommended/CardSliderRecommended.module.scss
  src/components/common/Card/CardSlider/Recommended/index.tsx
  src/components/common/Card/CardSlider/Similar/CardSliderSimilar.module.scss
  src/components/common/Card/CardSlider/Similar/index.tsx
  src/pages/test/cardslider/CardSliderPage.module.scss
  src/pages/test/cardslider/index.tsx
Labels: feat

#160 [봉찬] 레이아웃 IntroView
  public/images/pawing-background.png
  src/assets/svgs/logo.svg
  src/assets/svgs/pawing-market.svg
  src/assets/svgs/share.svg
  src/components/common/Icon/LogoFull/LogoFull.module.scss
  src/components/common/Icon/LogoFull/index.tsx
  src/components/common/Layout/IntroView/IntroView.module.scss
  src/components/common/Layout/IntroView/index.tsx
  src/components/common/Layout/Root/RootLayout.module.scss
  src/components/common/Layout/Root/index.tsx
  src/components/common/Nav/Bottom/NavBottom.module.scss
  src/hooks/useCopyClipboard.ts
  src/pages/HomePage.module.scss
  src/pages/index.tsx
  src/styles/mixin.scss
  src/styles/sizes.scss
Labels: feat

#175 [봉찬] CardSlider 높이 변경
  src/components/common/Card/CardSlider/Base/List/CardSliderList.module.scss
Labels: refactor

#179 [봉찬] ToastProvider 리렌더링 버그 해결
  src/components/common/Toast/Provider/index.tsx
  src/pages/index.tsx
Labels: bug

#184 [서인] signup, profile 페이지 / 닉네임 중복 검사 구현
  src/apis/imageAPI.ts
  src/apis/userApi.ts
  src/assets/images/sadly-pet.png
  src/assets/images/selected-cat.png
  src/assets/images/selected-dog.png
  src/assets/images/unselected-cat.png
  src/assets/images/unselected-dog.png
  src/assets/images/welcome-cat.png
  src/assets/images/welcome-dog.png
  src/assets/images/welcome-pet.png
  src/components/auth/Menu/index.tsx
  src/components/auth/SignupForm/index.tsx
  src/components/common/Input/index.tsx
  src/pages/my/index.tsx
  src/pages/my/info/Info.module.scss
  src/pages/my/info/index.tsx
  src/pages/my/profile/Profile.module.scss
  src/pages/my/profile/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/onboarding/welcome.tsx
  src/pages/signup/index.tsx
  src/utils/checkNickname.ts
  src/utils/signupFormSchema.ts
Labels: feat

#182 [봉찬] 라우터 로딩 적용
  src/assets/lotties/check.json
  src/assets/lotties/pawing-loading.json
  src/components/common/Loading/Loading.module.scss
  src/components/common/Loading/index.tsx
  src/hooks/useLoading.ts
  src/pages/_app.tsx
  src/pages/payment/paymentSuccess.tsx
  src/pages/test/loading/LoadingPage.module.scss
  src/pages/test/loading/index.tsx
Labels: feat

#188 [봉찬] Toast 메세지 줄바꿈 이슈
  src/components/common/Toast/Toast.module.scss
Labels: refactor

#180 [서인] onboarding, welcome, 프로필 수정 페이지 / API 연결
  package-lock.json
  package.json
  src/components/auth/SignupForm/index.tsx
  src/pages/my/profile/index.tsx
Labels: feat

#195 [봉찬] 페이지 이동 시 토스트 유지
  src/components/common/Toast/Provider/index.tsx
  src/pages/_app.tsx
Labels: refactor

#202 [서인] 프로필 수정 페이지 / 이미지 삽입
  next.config.mjs
  src/apis/imageAPI.ts
  src/apis/userApi.ts
  src/components/auth/Menu/index.tsx
  src/components/auth/SignupForm/SignupForm.module.scss
  src/pages/my/info/Info.module.scss
  src/pages/my/profile/Profile.module.scss
  src/pages/my/profile/index.tsx
Labels: feat

#196 [서인] 프로필 수정, 회원 정보 페이지 / 토스트 적용
  src/pages/my/index.tsx
  src/pages/my/info/index.tsx
  src/pages/my/profile/index.tsx
  src/utils/signupFormSchema.ts
Labels: feat

#204 [봉찬] aws 수정 및 http 허용 meta 태그 추가
  scripts/aws-deploy.sh
  src/pages/_app.tsx
Labels: refactor

#200 [송은] 버튼 컴포넌트 type prop 추가
  src/components/common/Button/index.tsx
Labels: refactor

#190 [민영] myReviewPage API 일부 연결
  package-lock.json
  src/apis/myReviewAPI.ts
  src/pages/my/review/write/index.tsx
Labels: feat

#215 [서인] 내 리뷰 / API 연결
  next.config.mjs
  src/apis/imageApi.ts
  src/apis/myReviewAPI.ts
  src/apis/purchase/api.ts
  src/apis/purchase/queries.ts
  src/components/auth/Menu/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Card/Card.module.scss
  src/components/common/Card/index.tsx
  src/components/review/ReviewCard/ReviewCard.module.scss
  src/components/review/ReviewCard/index.tsx
  src/components/review/WroteReviewCard/WroteReviewCard.module.scss
  src/components/review/WroteReviewCard/index.tsx
  src/pages/my/order/index.tsx
  src/pages/my/profile/index.tsx
  src/pages/my/review/Review.module.scss
  src/pages/my/review/index.tsx
  src/utils/signupFormSchema.ts
Labels: feat

#212 [송은] deliveryAddPage
  src/components/common/DeliveryCard/index.tsx
  src/components/common/Input/Input.module.scss
  src/components/order/OrderDeliveryCard/OrderDeliveryCard.module.scss
  src/components/order/OrderDeliveryCard/index.tsx
  src/components/payment/AddressInput.module.scss
  src/components/payment/AddressInput.tsx
  src/hooks/useAddAddressInfo.ts
  src/hooks/useUpdateAddressInfo.ts
  src/pages/my/delivery/add/Add.module.scss
  src/pages/my/delivery/add/index.tsx
  src/pages/my/delivery/edit/Edit.module.scss
  src/pages/my/delivery/edit/[id].tsx
  src/pages/my/delivery/index.tsx
  src/pages/payment/Payment.module.scss
  src/pages/payment/delivery/Delivery.module.scss
  src/pages/payment/delivery/index.tsx
  src/pages/payment/index.tsx
  src/types/components/delivery.ts
  src/utils/deliveryFormSchema.ts
Labels: feat

#221 [서인] 빌드 에러 수정
  src/components/payment/TotalPay.tsx
  src/pages/my/order/detail.tsx
Labels: feat

#220 [송은] feat/productDetailPage
  next.config.mjs
  src/assets/svgs/arrow-down-pink.svg
  src/assets/svgs/arrow-up-pink.svg
  src/assets/svgs/btn-share.svg
  src/assets/svgs/delivery.svg
  src/assets/svgs/ic-x.svg
  src/assets/svgs/mascot-share-link.svg
  src/components/common/Carousel/Product/ProductCarousel.module.scss
  src/components/common/Carousel/Product/index.tsx
  src/components/productDetails/detailedDescription/DetailedDescription.module.scss
  src/components/productDetails/detailedDescription/index.tsx
  src/components/productDetails/orderPolicy/OrderPolicy.module.scss
  src/components/productDetails/orderPolicy/index.tsx
  src/components/productDetails/productInfo/ProductInfo.module.scss
  src/components/productDetails/productInfo/index.tsx
  src/components/productDetails/similarProducts/SimilarProducts.module.scss
  src/components/productDetails/similarProducts/index.tsx
  src/hooks/useUpdateAddressInfo.ts
  src/pages/products/ProductDetail.module.scss
  src/pages/products/[id].tsx
  src/pages/refund/policy/Policy.module.scss
  src/pages/refund/policy/index.tsx
  src/types/product.ts
  src/utils/getFutureDate.ts
Labels: feat

#222 [민영] optionBottomSheet
  src/components/common/Dropdown/index.tsx
  src/components/common/Team/TeamDataCard.tsx
  src/components/product/OptionBottomSheet.module.scss
  src/components/product/OptionBottomSheet.tsx
  src/pages/test/team/index.tsx
Labels: feat

#231 [민영] 상품상세페이지 공동구매, 리뷰 컴포넌트 연결
  src/components/common/Team/HighlightTeam.module.scss
  src/components/common/Team/HighlightTeam.tsx
  src/components/common/Team/TeamDataCard.tsx
  src/components/common/review/HighlightReview.module.scss
  src/components/common/review/HighlightReview.tsx
  src/components/common/review/RatingBox.tsx
  src/components/common/review/ReviewBox.module.scss
  src/components/common/review/ReviewBox.tsx
  src/components/common/review/StarRating.tsx
  src/pages/products/[id].tsx
  src/pages/team/TeamPage.module.scss
  src/pages/team/index.tsx
  src/pages/test/team/index.tsx
Labels: feat

#229 [봉찬] Home 페이지
  next.config.mjs
  src/apis/cart/queries.ts
  src/apis/product/api.ts
  src/apis/product/queries.ts
  src/assets/images/github.png
  src/assets/svgs/pet-food.svg
  src/assets/svgs/pet-goods.svg
  src/assets/svgs/pet-snack.svg
  src/components/common/Button/Cart/index.tsx
  src/components/common/Button/PetToggle/PetToggleButton.module.scss
  src/components/common/Button/PetToggle/index.tsx
  src/components/common/Button/PetType/PetTypeButton.module.scss
  src/components/common/Button/PetType/index.tsx
  src/components/common/Button/ProductType/ProductTypeButton.module.scss
  src/components/common/Button/ProductType/index.tsx
  src/components/common/Card/CardSlider/Hot/index.tsx
  src/components/common/Card/CardSlider/Recommended/index.tsx
  src/components/common/Card/CardSlider/Similar/index.tsx
  src/components/common/Card/index.tsx
  src/components/common/GitHubBox/GitHubBox.module.scss
  src/components/common/GitHubBox/index.tsx
  src/components/common/Layout/Root/RootLayout.module.scss
  src/components/common/Nav/Bottom/NavBottom.module.scss
  src/components/home/CategoryBox/CategoryBox.module.scss
  src/components/home/CategoryBox/index.tsx
  src/data/topMenus.json
  src/pages/HomePage.module.scss
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/test/my.tsx
  src/types/apis/product.types.ts
  src/types/components/petTypeButton.ts
  src/types/components/productTypeButton.ts
  src/utils/getProductsSearchParams.ts
  src/utils/queryClient.ts
Labels: feat

#234 [송은] fix/producDetailPage
  src/pages/products/[id]/ProductDetail.module.scss
  src/pages/products/[id]/index.tsx
Labels: refactor

#228 [봉찬] proxy destination env로 관리
  next.config.mjs
Labels: refactor

#236 [송은] 카드 컴포넌트 extraLarge 사이즈 추가
  src/components/common/Card/Card.module.scss
  src/components/common/Card/CardSlider/Hot/index.tsx
  src/components/common/Card/CardSlider/Recommended/index.tsx
  src/components/common/Card/CardSlider/Similar/index.tsx
  src/components/common/Card/index.tsx
  src/components/productDetails/similarProducts/index.tsx
  src/pages/my/order/empty.tsx
  src/pages/test/card/index.tsx
Labels: refactor

#237 [지원] deliveryId 값 받아오기, 배송메시지 미입력시 버튼 비활성화
  package-lock.json
  src/pages/cart/Cart.module.scss
  src/pages/payment/index.tsx
  src/pages/payment/paymentSuccess.tsx
Labels: refactor

#238 [서인] myorder / API 연결
  src/apis/purchase/api.ts
  src/components/auth/LoginButton/Login.module.scss
  src/components/auth/Menu/Menu.module.scss
  src/components/auth/SignupForm/SignupForm.module.scss
  src/components/cart/TotalPay.tsx
  src/components/common/Button/NextButton/NextButton.module.scss
  src/components/common/Card/Card.module.scss
  src/components/common/Card/index.tsx
  src/components/order/Empty/Empty.module.scss
  src/components/order/Empty/index.tsx
  src/components/order/OrderCard/OrderCard.module.scss
  src/components/order/OrderCard/index.tsx
  src/components/order/OrderFilterBar/OrderFilterBar.module.scss
  src/pages/my/My.module.scss
  src/pages/my/order/Order.module.scss
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/detail.tsx
  src/pages/my/order/index.tsx
  src/pages/my/review/index.tsx
  src/pages/products/[id]/index.tsx
  src/utils/getTagText.ts
Labels: feat

#244 [송은] fix: detail 없을 떄 기본이미지 설정
  src/components/common/Carousel/Product/index.tsx
  src/components/productDetails/detailedDescription/index.tsx
  src/components/productDetails/productInfo/index.tsx
  src/pages/products/[id]/index.tsx
Labels: bug

#239 [봉찬] 추천상품 페이지
  src/apis/product/queries.ts
  src/assets/svgs/arrow-top-white.svg
  src/components/auth/Menu/index.tsx
  src/components/common/Button/PetToggle/index.tsx
  src/components/common/Button/ScrollTop/ScrollTopButton.module.scss
  src/components/common/Button/ScrollTop/index.tsx
  src/components/common/Card/CardList/Recommended/CardListRecommended.module.scss
  src/components/common/Card/CardList/Recommended/index.tsx
  src/components/common/Card/CardSlider/Hot/index.tsx
  src/components/common/Card/CardSlider/Recommended/index.tsx
  src/components/common/Card/CardSlider/Similar/index.tsx
  src/components/common/GitHubBox/GitHubBox.module.scss
  src/components/common/GitHubBox/index.tsx
  src/components/common/Nav/Bottom/index.tsx
  src/components/common/Toast/Toast.module.scss
  src/pages/products/recommended/ProductRecommendedPage.module.scss
  src/pages/products/recommended/index.tsx
  src/pages/test/my.tsx
  src/styles/z-index.scss
  src/utils/getFirstQueryParam.ts
Labels: feat

#249 [민영] 상품상세페이지 리뷰 전체보기 페이지 연결, 리뷰 전체보기 페이지 sortButton 적용, 공동구매 웹소켓 세팅
  package-lock.json
  package.json
  src/components/common/Team/HighlightTeam.tsx
  src/components/common/review/HighlightReview.tsx
  src/pages/products/[id]/review/ReviewPage.module.scss
  src/pages/products/[id]/review/index.tsx
  src/pages/products/[id]/team/TeamPage.module.scss
  src/pages/products/[id]/team/index.tsx
  src/pages/test/review/index.tsx
  src/types/apis/groupBuying.ts
  src/types/product.ts
Labels: feat

#242 [지원] 로그인 없이 장바구니로 이동 시 my 페이지 렌더링
  src/pages/cart/index.tsx
Labels: bug

#247 [봉찬] 카테고리 페이지
  src/components/common/Button/ProductType/ProductTypeButton.module.scss
  src/components/common/Button/ScrollTop/index.tsx
  src/components/common/Card/CardList/Basic/CardListBasic.module.scss
  src/components/common/Card/CardList/Basic/index.tsx
  src/hooks/useTargetHeightShow.ts
  src/pages/products/category/ProductCategoryPage.module.scss
  src/pages/products/category/index.tsx
  src/types/apis/product.types.ts
  src/utils/getProductsSearchParams.ts
Labels: feat

#250 [서인] 주문, 리뷰 페이지 / 주문 필터 구현, 리뷰 페이지 API 연결
  src/apis/myReviewAPI.ts
  src/components/common/Card/index.tsx
  src/components/order/Empty/Empty.module.scss
  src/components/order/Empty/index.tsx
  src/components/order/OrderFilterBar/index.tsx
  src/pages/my/order/Order.module.scss
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/index.tsx
  src/pages/my/review/index.tsx
Labels: feat

#254 [민영] 리뷰작성페이지 쿼리 처리
  src/pages/my/review/write/index.tsx
Labels: feat

#255 [민영] paymentClientKey env 처리
  src/pages/payment/index.tsx
Labels: refactor

#256 [민영] 리뷰 전체보기, 공동구매 전체보기 페이지 BackButton 경로 수정, 401 페이지 구현
  src/components/common/NoAccess/NoAccess.module.scss
  src/components/common/NoAccess/index.tsx
  src/components/common/review/ReviewBox.tsx
  src/pages/noAccess/NoAccessPage.module.scss
  src/pages/noAccess/index.tsx
  src/pages/products/[id]/review/index.tsx
  src/pages/products/[id]/team/index.tsx
Labels: feat, bug, refactor

#258 [서인] 리뷰 데이터, 구매 데이터 쿼리 전달
  src/pages/my/review/index.tsx
  src/pages/my/review/write/index.tsx
Labels: feat

#261 [서인] 로그인 페이지 / 로그인 서버 로컬 분리
  src/components/auth/LoginButton/GoogleLogin.tsx
  src/components/auth/LoginButton/KakaoLogin.tsx
  src/components/order/OrderCard/OrderCardButton.tsx
  src/components/order/OrderCard/index.tsx
  src/components/order/OrderFilterBar/index.tsx
  src/pages/auth/google/callback.tsx
  src/pages/auth/kakao/callback.tsx
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/detail.tsx
Labels: feat

#265 [서인] 주문, 주문 상세 페이지 / 주문 카드 버튼 구현
  src/apis/purchase/api.ts
  src/components/common/Card/index.tsx
  src/components/order/OrderCard/OrderCard.module.scss
  src/components/order/OrderCard/OrderCardButton.tsx
  src/components/order/OrderCard/index.tsx
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/index.tsx
  src/utils/getTagText.ts
Labels: feat

#272 [서인] 회원가입, 로그인, 마이, 온보딩 / QA 이슈 해결
  src/apis/axiosInstance.ts
  src/components/auth/SignupForm/UserAgreement.tsx
  src/components/auth/SignupForm/index.tsx
  src/components/common/Input/index.tsx
  src/pages/my/info/index.tsx
  src/pages/my/order/index.tsx
  src/pages/my/profile/Profile.module.scss
  src/pages/my/profile/index.tsx
  src/pages/my/review/index.tsx
  src/pages/onboarding/Onboarding.module.scss
  src/pages/onboarding/index.tsx
  src/utils/checkNickname.ts
Labels: bug

#273 [민영] 리뷰 상세보기 페이지 구현
  src/apis/myReviewAPI.ts
  src/components/common/review/ReviewProductDataCard.tsx
  src/components/review/WroteReviewCard/index.tsx
  src/pages/my/review/[reviewId]/index.tsx
  src/pages/my/review/index.tsx
  src/pages/my/review/write/index.tsx
  src/types/review.ts
Labels: feat

#279 [서인] 주문 내역, 내 리뷰 / QA
  src/components/auth/LoginButton/GoogleLogin.tsx
  src/components/auth/Menu/index.tsx
  src/components/cart/TotalPay.tsx
  src/components/order/Empty/Empty.module.scss
  src/components/order/OrderFilterBar/index.tsx
  src/components/review/WroteReviewCard/index.tsx
  src/pages/my/info/index.tsx
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/index.tsx
  src/pages/my/profile/index.tsx
  src/pages/my/review/index.tsx
  src/pages/onboarding/index.tsx
  src/utils/signupFormSchema.ts
Labels: bug

#274 [지원] 이슈
  src/components/cart/Card.tsx
  src/components/cart/TotalPay.module.scss
  src/components/payment/Card.tsx
  src/components/payment/PaymentAgree.module.scss
  src/components/payment/PaymentAgree.tsx
  src/components/payment/TotalPay.module.scss
  src/components/payment/TotalPay.tsx
  src/pages/payment/index.tsx
Labels: bug

#275 [봉찬] 카드리스트 여백 임시 처리...
  src/components/common/Card/CardList/Category/CardListCategory.module.scss
  src/components/common/Card/CardList/Hot/CardListHot.module.scss
  src/components/common/Card/CardList/Recommended/CardListRecommended.module.scss
  src/components/common/Card/CardList/Search/CardListSearch.module.scss
  src/components/common/Card/CardList/Zzim/CardListZzim.module.scss
Labels: refactor

#277 [봉찬] AWS CI/CD 제거
  .github/workflows/aws-deploy.yml
  appspec.yml
  scripts/aws-deploy.sh
Labels: refactor

#280 [봉찬] 스크롤 디자인
  src/styles/reset.scss
Labels: feat

#282 [봉찬] favicon 설정
  public/images/favicon.ico
  public/images/favicon.svg
  src/pages/_document.tsx
Labels: feat

#287 [송은] fix/songeun
  src/components/common/Card/CardSlider/Recommended/index.tsx
  src/components/common/Card/index.tsx
  src/components/product/OptionBottomSheet.tsx
  src/pages/products/[id]/index.tsx
  src/pages/products/[id]/team/index.tsx
  src/types/apis/product.ts
Labels: bug

#289 [송은] Fix/songeun2
  src/components/product/NumberInput.tsx
  src/components/product/OptionBottomSheet.tsx
  src/pages/products/[id]/index.tsx
Labels: bug

#292 [서인] 주문, 내 리뷰 페이지 / QA 이슈 해결
  src/components/auth/SignupForm/index.tsx
  src/components/order/OrderCard/OrderCard.module.scss
  src/components/review/WroteReviewCard/WroteReviewCard.module.scss
  src/pages/my/info/index.tsx
  src/pages/my/order/Order.module.scss
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/index.tsx
  src/pages/my/review/index.tsx
  src/utils/signupFormSchema.ts
Labels: bug

#294 [민영] TeamDataCard nickname 버그 수정
  src/components/common/Team/TeamDataCard.tsx
Labels: bug

#296 [서인] 프로필 수정 이슈 해결
  src/components/review/ReviewCard/ReviewCard.module.scss
  src/pages/my/profile/index.tsx
  src/pages/my/review/Review.module.scss
Labels: bug

#302 [서인] 리드미 작성
  README.md
Labels: feat

#299 [봉찬] 상품상세 페이지 찜 반영
  src/pages/products/[id]/index.tsx
Labels: bug
