Repository Together-3team/petFrontend, pull requests merged in 2024-07, with the labels that each got.

#305 [서인] 리드미 페이지 움짤 크기 수정 / 이미지 링크 걸기
  README.md
Labels: refactor

#304 [봉찬] 배너 캐러셀 object-fit: cover 적용
  src/components/common/Carousel/Banner/BannerCarousel.module.scss
  src/components/common/Carousel/Banner/index.tsx
Labels: refactor

#309 Bug/크로스브라우징
  src/pages/my/profile/Profile.module.scss
  src/pages/onboarding/index.tsx
Labels: bug, refactor

#310 [서인] 마이, 회원가입, 배송지 / 연락처 하이픈 자동 입력
  next.config.mjs
  src/apis/imageApi.ts
  src/components/auth/SignupForm/index.tsx
  src/pages/my/delivery/add/index.tsx
  src/pages/my/delivery/edit/[id].tsx
  src/pages/my/info/index.tsx
  src/utils/insertPhoneNumberHyphen.ts
  src/utils/signupFormSchema.ts
Labels: refactor

#312 [정봉찬] 로딩 최적
  src/hooks/useLoading.ts
Labels: refactor

#313 [서인] refreshToken 교체 이슈 수정
  src/apis/axiosInstance.ts
  src/pages/my/info/index.tsx
  src/utils/signupFormSchema.ts
Labels: bug

#317 [정봉찬] 비로그인 상품 상세 페이지 404
  src/components/common/Card/CardSlider/Recommended/index.tsx
  src/pages/products/[id]/index.tsx
Labels: bug

#318 [서인] my 페이지 / 탠스택 쿼리 키 분리&적용
  src/apis/purchase/queries.ts
  src/apis/user/api.ts
  src/apis/user/queries.ts
  src/components/auth/Menu/index.tsx
  src/components/auth/SignupForm/index.tsx
  src/hooks/useAuth.ts
  src/pages/liked/index.tsx
  src/pages/my/index.tsx
  src/pages/my/info/index.tsx
  src/pages/my/order/[purchaseId].tsx
  src/pages/my/order/index.tsx
  src/pages/my/profile/index.tsx
  src/pages/my/review/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/onboarding/welcome.tsx
  src/pages/payment/delivery/index.tsx
  src/utils/checkNickname.ts
  src/utils/signupFormSchema.ts
Labels: refactor
